lessons/dom-manipulation-with-javascript.md

* Some minor typo fixes
* There were mismatching class names between a codepen and the lesson

Fix typos and class mismatching

---

lessons/jquery-dom-traversal-and-manipulation.md
today/2016-07-11.md

Link now takes you to the jquery dojo lesson

Fix jquery lesson link

---

lessons/jquery-dom-traversal-and-manipulation.md

Made a couple little grammar fixes and pointed the form link to a form rather than presidents.

Fix typos and link error

---

today/index.html

Changed the title of this weeks date range to not be the 4th

Fix Week of July 4 to be Week of July 11

---

today/2016-07-12.md

Change line 17 'litle' to 'little' :-)

---

lessons/being-successful-at-turing.html

But, then again, what isn't hacky in reveal?

Hacky fix for tiny potato image

---

lessons/html-basics.md
lessons/index.html
lessons/introduction-to-html.md

Started going through some of the early lessons and made some simple changes and fixes as I read through the copy. None of the changes are too drastic.

Some typo fixes & grammar tweaks in initial lessons

---

_includes/navigation.html

Just a random k. Those are dangerous.

Change Moduke 3 to Module 3

---

today/2016-10-10.md

fixed weatherly project link

---

projects/weathrly.md

I added the link to the API under required technologies

added API link

---

lessons/testing-react.md

quick typo fix

---

lessons/index.html
lessons/testing-react-with-stubs.md
lessons/testing-react.md

This PR represents the work towards a Mod 2 lesson for testing React using Mocks/Stubs/Spies
Currently a WIP - so that students can observe the growth of the lesson

React Testing: Stubs/Mocks/Spies

---

_includes/navigation.html

I did a thing to link to a thing.

Add Github Profiles Link to Navbar

---

_includes/navigation.html
calendars/index.html

- Consolidates multiple calendar links from the sidebar into one sidebar index list

Clean Up Calendar Navigation

---

_includes/navigation.html
open-source/index.html
open-source/os-guide.md

Adds a guide to open source and begins a list of projects

Add Open Source Info

---

projects/2DoBox-Pivot.md

2dobox Updates

---

portal/index.html
portal/lesson-notes/data-structures/bitwise.md
portal/lesson-notes/data-structures/bst.md
portal/lesson-notes/data-structures/huffman.md
portal/lesson-notes/data-structures/index.html
portal/lesson-notes/data-structures/killing-time.md
portal/lesson-notes/data-structures/linkedlist.md
portal/lesson-notes/index.html
portal/lesson-notes/module-2/intro-to-react.md
portal/lesson-notes/module-2/refactor-shoot-breeze.md
portal/lesson-notes/module-2/wai-aria-notes.md
portal/lesson-notes/random-notes/mentor-feedback-angular.md

Adds a portal. For portalling.

Instructor resources

---

projects/imposter-syndrome.md

Fix more of Steve's oops in Imposter Syndrome markdown.

Fix imposter

---

projects/index.html
projects/mod-4-assignments-assignment.md

@brittanystoroz @Alex-Tideman 
Here is a first draft of the 'optional' homework project
Will discuss later, but idea is that in place of the point system - you can boner out on one project and still graduate - but collecting your additional assignments in a professional manner is considered a project. That way we can assign whatever cool stuff we want and not hunt down points like a hawk.

First Draft of Homework Project

---

projects/jet-fuel.md

@brittanystoroz @rrgayhart
Updating the Jet Fuel Node Project to include persisting data to SQL and up'ing the project points to total 150 with a possible 25 extra points.

Update project spec to 150 points with SQL requirement

---

lessons/how-to-build-a-state-tree-aka-wtf-is-redux.md

Lesson plan for next week on how to build a state tree!
@martensonbj @Alex-Tideman

State Tree Lesson For Next Week (Thursday 2/2/2017)

---

lessons/module-4/syllabus-overview.md

First draft of the mod 4 scope and sequence doc

M4 Syllabus Page

---

lessons/node.md

was re-reading the lesson and figured it wouldn't hurt to help update the lesson.

Update multiple typos in node.md

---

lessons/module-2/create-your-own-npm-module-ML.md

build-an-npm-module-mod2.md

---

lessons/module-1/pr-practice.md

Added in information about my weird job.

Holt Weird Job

---

lessons/module-1/pr-practice.md

Francy's weird job.

---

lessons/module-1/pr-practice.md

add my weirdest job to the list because I was told to.

Alex Banister-weirdest job update

---

lessons/module-1/pr-practice.md

Updated matt renn's weirdest job

matt renn update pr practice

---

lessons/module-1/pr-practice.md

Jason Hughes

---

lessons/module-1/pr-practice.md

I edited the file to include my weirdest job.

Add my weirdest job

---

lessons/module-1/pr-practice.md

Erik Ingvalson

---

lessons/module-1/pr-practice.md

I can't think of one... cart pusher.

My weirdest job?

---

lessons/module-1/pr-practice.md

did a thing

---

lessons/module-1/pr-practice.md

Detailed interesting job I had as a child.

Add response to weirdest job question

---

lessons/module-1/pr-practice.md

Update pr-practice.md with jen's job

Update pr-practice.md with Jen's job

---

lessons/module-1/pr-practice.md

This a bit of detail to give an answer to Nick Teets' weirdest job

Updated nick teets weirdest job

---

prework/index.html

Line 18: 
**change-**
“ web developer **be** the end of the 4th module.” to
“ web developer **by** the end of the 4th module.” 
Line 190:
**change-**
"**What** is it useful to use external stylesheets" to
"**When** is it useful to use external stylesheets"

Fix two grammatical errors

---

projects/2DoBox-Pivot-Mod1.md

Fix grammatical errors

---

lessons/module-2/test-driven-development.md

Make some additions to the TDD lesson

---

projects/complete-me.md

Hey @letakeane and @brittanystoroz I edited this project spec. I'd love some feedback!

edited complete-me project spec

---

lessons/module-1/js-3-dom-manipulation.md

Change event link that has clearer doc on event listeners.

Change event link that has clearer docs.

---

lessons/module-1/introduction-to-testing-javascript.md

Add Learning Goals for Testing.
Moved order of one part of lesson to align with TDD.
Add more Your Turns for students to digest content.
Add information/examples about importing and exporting files for testing.

Add more content and checks into test lesson.

---

projects/build-your-own-backend.md

- Updated the project spec of BYOB to reflect the two week project
- Added info about week 1 BE and week 2 FE expectations
- Included testing as a primary learning goal
- Added second learning goal of professional workflow habits, including better use of PR process and creation of documentation
- I removed the references to JWTs from project description and rubrics since I'm not sure where those fit.
- I'm working on documentation for the mini-open-source requirement and will be posting that shortly; I'd love another set of eyes on that too.

Update BYOB spec to two-week project

---

projects/ideabox-groups.md
projects/index.html

Lemme know what y'all think! I can merge if its easier to review after the md has been converted to html

Add ideabox group version

---

projects/foto-finder-final.md

Also add info about running a server to open their app.

Add information about converting blob into URL

---

lessons/module-1/introduction-to-flexbox.html

Reordered the lesson plan for flexbox. Shouldn't cause any issues.

Change order of slides for Flexbox lesson

---

lessons/module-1/json-and-localstorage.md

Made some edits and added in code pen exercises for the lesson

Json loc storage edits

---

lessons/module-1/json-and-localstorage.md

Added new codepens to the lesson for improved clarity

Update CodePens and lesson length

---

lessons/module-1/css-1.md

@khalidwilliams @ameseee I added a short section about combinator selectors for CSS. We cover specificity later in the lesson and mention some combinators there, but never explicitly teach it.
I also figure that it would be a pretty high-level, "you can also target things this way..." portion of the lesson.
Lemme know if you have any feedback!

Add combinators

---

lessons/module-1/js-4.md

Update Try it section to include reassigning a value _and_ adding a new property.

Add practice opportunity to add properties to an object

---

_sass/content.scss
lessons/index.html

I thought it might be nice if we could all write a sentence or two describing the goals/focuses of our Mod under our lesson plan sections. More for the general public who might be landing on our site or potential students that want to get a better feel for what we’re teaching/when and why. 
It could look something like this? I also thought it might help break up the monotony of the page a bit since it’s literally just a giant list of links

Add mod descriptions
